<?php

/**
 * PluginMGAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMGAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMGAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMGAlbum');
    }
}