<?php

/**
 * PluginMGGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class PluginMGGallery extends BaseMGGallery
{
  public function getAlbum() {
    return $this->getMGAlbum();
  }

  public function getCountPhotos() {
    return $this->getPhotos()->count();
  }
}