<?php

/**
 * PluginMGGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMGGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMGGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMGGallery');
    }
}