<?php

/**
 * PluginMGPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMGPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMGPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMGPhoto');
    }
}