<?php

/**
 * PluginMGGalleryPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMGGalleryPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMGGalleryPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMGGalleryPhoto');
    }
}