all:
  sfMooDooGalleryPlugin:
    dirname:                    mooDooGallery
    upload_dir:                 %SF_UPLOAD_DIR%/mooDooGallery
    images_dir:                 %SF_WEB_DIR%/images/mooDooGallery
    web_dir:                    /uploads/mooDooGallery
    no_image_name:              moodoo_no_image_

    # lightbox
    add_milkbox:                true
    add_mootools-core:          false
    add_mootools-more:          false

    generate_images:            true

    image_size:
      tiny:
        width:                  32
        height:                 32
      avatar:
        width:                  256
        height:                 256
      preview:
        width:                  300
        height:                 null