# mooDooGalley Album
MGAlbum:
  actAs:
    - Timestampable
  tableName:                    mdgalledy_album
  columns:
    id:                         {type: integer, primary: true, autoincrement: true}
    author_id:                  integer(4)
    title:                      {type: string(100), notnull: true}
    description:                {type: clob}
  relations:
    Galleries:                  {type: many, class: MGGallery, local: id, foreign: album_id}

# mooDooGalley Gallery
MGGallery:
  actAs:
    - Timestampable
  tableName:                    mdgalledy_gallery
  columns:
    id:                         {type: integer, primary: true, autoincrement: true}
    album_id:                   {type: integer}
    author_id:                  integer(4)
    title:                      {type: string(100), notnull: true}
    description:                {type: clob}
  relations:
    Photos:                     {type: many, class: MGPhoto, local: id, foreign: gallery_id}
    Album:                      {local: album_id, foreign: id, foreignAlias: Album}

# mooDooGalley Photo
MGPhoto:
  actAs:
    - Timestampable
  tableName:                    mdgalledy_photo
  columns:
    id:                         {type: integer, primary: true, autoincrement: true}
    gallery_id:                 {type: integer}
    author_id:                  integer(4)
    title:                      {type: string(100), notnull: true}
    description:                {type: clob}
    photo:                      {type: string(255), notnull: true}
  relations:
    Gallery:                    {local: gallery_id, foreign: id, foreignAlias: Gallery}


# mooDooGalley Categories
MGCategory:
  actAs:
    - Timestampable
  tableName:                    mdgalledy_category
  columns:
    id:                         {type: integer, primary: true, autoincrement: true}
    title:                      {type: string(100), notnull: true}
    description:                {type: clob}